version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 6543:5432
    volumes:
      - ./apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=example_db_skinx